apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
  labels:
    app: spring-boot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app:spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      containers:
      - name: spring-boot-demo-container
        image: crpi-ux0tzkesro0x54i3.cn-hangzhou.personal.cr.aliyuncs.com/hsbccn/lishuangquan:1.0.0
        ports:
        - containerPort: 8080
