spring.application.name=antiFraud

# ???????
spring.datasource.url=jdbc:mysql://localhost:3306/hsbc
spring.datasource.username=root
spring.datasource.password=wrtgj840929
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.data.jpa.repositories.base-package=com.hsbc.antifraud.repository, com.hsbc.antifraud.entity

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
